DigiComp:
  FlowWkhtmlToPdfAdapter:
    binary:
      pdf: '/usr/bin/wkhtmltopdf'
    useXvfb: false
    timeout: 60
Neos:
  Flow:
    object:
      excludeClasses:
        knplabs.knpsnappy:
          - autoload
