DigiComp:
  FlowWkhtmlToPdfAdapter:
    binary:
      pdf: '/usr/bin/wkhtmltopdf'
    useXvfb: FALSE
    timeout: 60

TYPO3:
  Flow:
    object:
      excludeClasses:
        'knplabs.knpsnappy' : ['autoload']